export default {
    FETCH_LOCATION_START: 'FETCH_LOCATION_START',
    FETCH_LOCATION_SUCCESS: 'FETCH_LOCATION_SUCCESS',
    FETCH_LOCATION_FAILURE: 'FETCH_LOCATION_FAILURE',
    FETCH_WEATHER_START: 'FETCH_WEATHER_START',
    FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
    FETCH_WEATHER_FAILURE: 'FETCH_WEATHER_FAILURE',
    FETCH_ALERTS_START: 'FETCH_ALERTS_START',
    FETCH_ALERTS_SUCCESS: 'FETCH_ALERTS_SUCCESS',
    FETCH_ALERTS_FAILURE: 'FETCH_ALERTS_FAILURE',
}