export default {
    FETCH_SENSORDATA_START: 'FETCH_SENSORDATA_START',
    FETCH_SENSORDATA_SUCCESS: 'FETCH_SENSORDATA_SUCCESS',
    FETCH_SENSORDATA_FAILURE: 'FETCH_SENSORDATA_FAILURE',
    SET_SENSOR_ALERT: 'SET_SENSOR_ALERT',
    FETCH_CROPSCORE_START: 'FETCH_CROPSCORE_START',
    FETCH_CROPSCORE_SUCCESS: 'FETCH_CROPSCORE_SUCCESS',
    FETCH_CROPSCORE_FAILURE: 'FETCH_CROPSCORE_FAILURE'
}