export default {
    FETCH_USERS_START: 'FETCH_USERS_START',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    PUSH_ALERT_NOTIFICATION_START: 'PUSH_ALERT_NOTIFICATION_START',
    PUSH_ALERT_NOTIFICATION_SUCCESS: 'PUSH_ALERT_NOTIFICATION_SUCCESS',
    PUSH_ALERT_NOTIFICATION_FAILURE: 'PUSH_ALERT_NOTIFICATION_FAILURE'
};